import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link
          rel="stylesheet"
          href="/assets/css/plugins/owl-carousel/owl.carousel.css"
        />
        <link
          rel="stylesheet"
          href="/assets/css/plugins/magnific-popup/magnific-popup.css"
        />
        <link
          rel="stylesheet"
          href="/assets/css/plugins/jquery.countdown.css"
        />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/skins/skin-demo-3.css" />
        <link rel="stylesheet" href="/assets/css/demos/demo-3.css" />
      </head>
      <body className={inter.className}>
        <div className="page-wrapper">
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </div>

        <script src="/assets/js/jquery.min.js"></script>
        <script src="/assets/js/bootstrap.bundle.min.js"></script>
        <script src="/assets/js/jquery.hoverIntent.min.js"></script>
        <script src="/assets/js/jquery.waypoints.min.js"></script>
        <script src="/assets/js/superfish.min.js"></script>
        <script src="/assets/js/owl.carousel.min.js"></script>
        <script src="/assets/js/bootstrap-input-spinner.js"></script>
        <script src="/assets/js/jquery.plugin.min.js"></script>
        <script src="/assets/js/jquery.magnific-popup.min.js"></script>
        <script src="/assets/js/jquery.countdown.min.js"></script>

        <script src="/assets/js/main.js"></script>
        <script src="/assets/js/demos/demo-3.js"></script>
      </body>
    </html>
  );
}
